### ISSUE TITLE
Missing Project?

### ISSUE THREAD

**Issue by jlpm1009** [erossini/BlazorIdentityServerApi#1]
I was attempting to follow your [example ](https://www.puresourcecode.com/dotnet/blazor/secure-blazor-webassembly-with-identityserver4/)until I came across this statement:

Let’s open the CompanyEmployees.OAuth project and find the Configuration/InMemoryConfig class. Where do I find this project?  It seems without it you don't have a full working solution.

Thanks for your help,
Joel

**Comment by erossini** [comment]
Yes, you are right because in this code I use an existing `IdentityServer`.  You can find a lot of implementation of `IdentityServer` in my [blog here](https://www.puresourcecode.com/?s=identityserver). Let me know if you need the project for `CompanyEmployees.OAuth`.

**Comment by jlpm1009** [comment]
Thanks, I've been working with IdentityServer4 for about 2 years now so I know enough about it to say this... there are a lot of different ways to configure this tool.  So, without supplying an instance showing how you have it configured it makes me step away.  I've pretty much given up after 3 days of trying this.  I'm going back to blazor server and going from that direction.  I'm missing something so... I guess thats on me.  

PS.  Thanks for taking time to do your blog.  I know it is a commitment and I appreciate that you do it.

**Comment by erossini** [comment]
Hey,
I updated the code. Now you have a `CompanyEmployeesFullImplementation` folder where you have all the code.

**Comment by jlpm1009** [comment]
You are the man!  I'll check it out in the near future.
